# Generated by Django 2.2.3 on 2020-07-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0005_auto_20200708_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono'),
        ),
    ]
