# Generated by Django 2.2.3 on 2020-07-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0007_auto_20200713_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('addPatient', 'Agregar paciente'), ('viewPatient', 'Ver paciente'), ('deletePatient', 'Eliminar paciente'), ('updatePatient', 'Actualizar paciente')], 'verbose_name': 'paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
