# Generated by Django 2.2.3 on 2020-07-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0010_auto_20200713_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='patient_files', verbose_name='Foto'),
        ),
    ]
