# Generated by Django 2.2.3 on 2020-07-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0011_auto_20200713_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='patientfiles', verbose_name='Foto'),
        ),
    ]
