# Generated by Django 2.2.3 on 2020-07-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0015_auto_20200714_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Activo'),
        ),
    ]
