# Generated by Django 2.2.3 on 2020-07-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0017_auto_20200715_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
    ]
