# Generated by Django 2.2.3 on 2020-07-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0022_auto_20200720_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='direccion',
        ),
        migrations.AddField(
            model_name='address',
            name='patient',
            field=models.OneToOneField(
                default='', on_delete=django.db.models.deletion.CASCADE, to='apppatients.Patient'),
        ),
    ]
