# Generated by Django 2.2.3 on 2020-07-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0023_auto_20200720_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='patient',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='apppatients.Patient'),
        ),
    ]
