# Generated by Django 2.2.3 on 2020-07-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0027_auto_20200720_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Foto'),
        ),
    ]
