# Generated by Django 2.2.3 on 2020-07-21 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0028_auto_20200720_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del archivo')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción del archivo')),
                ('fechaSubida', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de subida')),
                ('path', models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='Archivo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='apppatients.Patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
    ]
