# Generated by Django 2.2.3 on 2020-07-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0032_auto_20200720_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='nombre',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre del archivo'),
        ),
    ]
