# Generated by Django 2.2.3 on 2020-07-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0034_auto_20200720_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': [('listFile', 'Listar archivos'), ('addFile', 'Agregar archivo'), ('deleteFile', 'Eliminar archivo')], 'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
    ]
