# Generated by Django 2.2.3 on 2021-01-02 02:53

import apppatients.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0042_remove_file_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSubida', models.CharField(max_length=50)),
                ('fechaSubida', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de subida')),
                ('path', models.FileField(blank=True, null=True, upload_to='upload-xls', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'importado',
                'verbose_name_plural': 'Importados',
                'permissions': [('importFile', 'Subir archivo')],
            },
            bases=(apppatients.mixins.AuditModel, models.Model),
        ),
    ]
