# Generated by Django 2.2.3 on 2021-01-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0043_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='tipoSubida',
            field=models.CharField(max_length=50, verbose_name='Tipo de fichero'),
        ),
    ]
