# Generated by Django 2.2.3 on 2021-01-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0049_auto_20210107_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='eliminado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Eliminado'),
        ),
    ]
