# Generated by Django 2.2.3 on 2021-01-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0050_patient_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='importado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Importado'),
        ),
    ]
