# Generated by Django 2.2.3 on 2021-01-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0051_import_importado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateCreate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
