# Generated by Django 2.2.3 on 2021-02-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0053_auto_20210118_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fechaAlta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha alta'),
        ),
    ]
