# Generated by Django 2.2.3 on 2021-02-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0054_auto_20210204_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fechaNacimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
    ]
