# Generated by Django 2.2.3 on 2021-02-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0055_patient_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
    ]
