# Generated by Django 2.2.3 on 2021-02-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0056_auto_20210204_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fechaUpdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha actualización'),
        ),
    ]
