# Generated by Django 2.2.3 on 2021-03-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0057_auto_20210205_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
