# Generated by Django 2.2.3 on 2021-03-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0058_auto_20210303_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
