# Generated by Django 2.2.3 on 2021-03-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0062_import_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='userName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
