# Generated by Django 2.2.3 on 2021-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0063_file_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='userName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='userName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
