# Generated by Django 2.2.3 on 2021-03-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0064_auto_20210304_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
