# Generated by Django 2.2.3 on 2021-03-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0065_delete_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navigation',
        ),
    ]
