# Generated by Django 2.2.3 on 2021-03-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0066_delete_navigation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Import',
        ),
    ]
