# Generated by Django 2.2.3 on 2021-03-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0067_delete_import'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
