# Generated by Django 2.2.3 on 2021-03-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0068_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
