# Generated by Django 2.2.3 on 2021-03-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0069_delete_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Propertie',
        ),
    ]
