# Generated by Django 2.2.3 on 2020-07-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
