# Generated by Django 2.2.3 on 2021-03-09 20:37

import apptasks.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('userCode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('userName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('nameTask', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la tarea')),
                ('descTask', models.CharField(blank=True, max_length=3999, null=True, verbose_name='Descripción de la tarea')),
                ('dateCreate', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación')),
                ('dateExecute', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ejecución')),
                ('status', models.BooleanField(blank=True, null=True, verbose_name='Estado de la tarea')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'permissions': [('listTask', 'Listar tareas'), ('addTask', 'Agregar tarea'), ('deleteTask', 'Eliminar tarea')],
            },
            bases=(apptasks.mixins.AuditModel, models.Model),
        ),
    ]
