# Generated by Django 2.2.3 on 2021-03-17 01:18

from django.db import migrations, models
import webtooth.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('userName', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fechaAlta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha alta')),
                ('fechaUpdate', models.DateTimeField(blank=True, null=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'permissions': [('addGroup', 'Agregar grupo'), ('viewGroup', 'Ver grupo'), ('deleteGroup', 'Eliminar grupo'), ('updateGroup', 'Actualizar grupo')],
            },
            bases=(webtooth.mixins.AuditModel, models.Model),
        ),
    ]
