# Generated by Django 2.2.3 on 2021-03-17 02:42

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphistory', '0005_auto_20210316_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='userName',
            field=models.CharField(blank=True, db_column='username', max_length=100, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
