# Generated by Django 2.2.3 on 2021-03-17 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apphistory', '0006_group_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='userName',
        ),
    ]
