# Generated by Django 2.2.3 on 2021-03-17 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webtooth.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('apppatients', '0070_delete_propertie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apphistory', '0008_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Grupo de estudio'),
        ),
        migrations.AlterField(
            model_name='study',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apphistory.Group', verbose_name='Grupo de Estudio'),
        ),
        migrations.AlterField(
            model_name='study',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Estudio'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(blank=True, null=True, verbose_name='Check')),
                ('fechaAlta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('fechaUpdate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha actualización')),
                ('estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apphistory.Study', verbose_name='Estudio')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apphistory.Group', verbose_name='Grupo de estudio')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apppatients.Patient', verbose_name='Paciente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historia',
                'permissions': [('addHistory', 'Agregar historia'), ('viewHistory', 'Ver historia'), ('deleteHistory', 'Eliminar historia'), ('updateHistory', 'Actualizar historia')],
            },
            bases=(webtooth.mixins.AuditModel, models.Model),
        ),
    ]
