# Generated by Django 2.2.3 on 2021-03-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apphistory', '0009_auto_20210316_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'permissions': [('addHistory', 'Agregar historia'), ('viewHistory', 'Ver historia'), ('deleteHistory', 'Eliminar historia'), ('updateHistory', 'Actualizar historia')], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historial'},
        ),
    ]
