# Generated by Django 2.2.3 on 2021-03-09 17:47

import webtooth.mixins
import appfiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('userName', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del archivo')),
                ('fechaSubida', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de subida')),
                ('path', models.FileField(blank=True, null=True, upload_to=appfiles.models.user_directory_path, verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'archivo',
                'verbose_name_plural': 'Archivos',
                'permissions': [('listFile', 'Listar archivos'), ('addFile', 'Agregar archivo'), ('deleteFile', 'Eliminar archivo')],
            },
            bases=(webtooth.mixins.AuditModel, models.Model),
        ),
    ]
