# Generated by Django 2.2.3 on 2020-07-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
