# Generated by Django 2.2.3 on 2020-07-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0004_auto_20200708_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fechaUpdate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha actualización'),
        ),
        migrations.AddField(
            model_name='patient',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fechaAlta',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha alta'),
        ),
    ]
