# Generated by Django 2.2.3 on 2020-07-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0006_auto_20200708_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('addPatient', 'Permiso para agregar paciente'), ('viewPatient', 'Permiso para ver pacientes')], 'verbose_name': 'paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
