# Generated by Django 2.2.3 on 2020-07-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0016_auto_20200714_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='numexp',
            field=models.CharField(max_length=15, verbose_name='Número de expediente'),
        ),
    ]
