# Generated by Django 2.2.3 on 2020-07-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0018_patient_rfc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Direction',
            new_name='Address',
        ),
    ]
