# Generated by Django 2.2.3 on 2020-07-20 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0019_auto_20200720_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='direccion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appGestionPacientes.Address'),
        ),
    ]
