# Generated by Django 2.2.3 on 2020-07-20 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0020_patient_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionPacientes.Address'),
        ),
    ]
