# Generated by Django 2.2.3 on 2020-07-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0024_auto_20200720_1414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Adress',
        ),
    ]
