# Generated by Django 2.2.3 on 2020-07-20 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0025_auto_20200720_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appGestionPacientes.Patient', verbose_name='Paciente'),
        ),
    ]
