# Generated by Django 2.2.3 on 2020-07-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0026_auto_20200720_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'permissions': [('viewAdress', 'Ver dirección')], 'verbose_name': 'dirección', 'verbose_name_plural': 'Direcciones'},
        ),
    ]
