# Generated by Django 2.2.3 on 2020-07-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0031_remove_file_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='upload', verbose_name='Archivo'),
        ),
    ]
