# Generated by Django 2.2.3 on 2020-07-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0033_file_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del archivo'),
        ),
    ]
