# Generated by Django 2.2.3 on 2020-07-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0035_auto_20200721_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': [('listFile', 'Listar archivos'), ('addFile', 'Agregar archivo'), ('deleteFile', 'Eliminar archivo')], 'verbose_name': 'archivo', 'verbose_name_plural': 'Archivos'},
        ),
    ]
