# Generated by Django 2.2.3 on 2020-07-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0036_auto_20200723_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('fechaConsulta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'bitácora',
                'verbose_name_plural': 'Bitácoras',
            },
        ),
    ]
