# Generated by Django 2.2.3 on 2020-07-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0037_requestlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestLog',
        ),
    ]
