# Generated by Django 2.2.3 on 2020-07-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0039_navigation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigation',
            options={'permissions': [('viewListNavigation', 'Ver historial de navegación')], 'verbose_name': 'navegación', 'verbose_name_plural': 'Navegaciones'},
        ),
    ]
