# Generated by Django 2.2.3 on 2021-01-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPacientes', '0052_auto_20210118_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateExecute',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ejecución'),
        ),
    ]
