# Generated by Django 2.2.3 on 2021-03-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('userCode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('permission', models.CharField(blank=True, max_length=3999, null=True, verbose_name='Permisos')),
                ('method', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de petición')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Url del servicio')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='Estado de la respuesta')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Datos enviados')),
                ('host', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP de origen')),
                ('file', models.CharField(blank=True, max_length=500, null=True, verbose_name='Archivo procesado')),
                ('varSession', models.TextField(blank=True, null=True, verbose_name='Variables de sesión')),
                ('eventTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Hora de la acción')),
            ],
            options={
                'verbose_name': 'navegación',
                'verbose_name_plural': 'Navegaciones',
                'permissions': [('viewListNavigation', 'Ver historial de navegación')],
            },
        ),
    ]
