# Generated by Django 2.2.3 on 2021-03-10 00:10

from django.db import migrations, models
import webtooth.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propertie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('key', models.CharField(max_length=100, verbose_name='key')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='value')),
            ],
            options={
                'verbose_name': 'propiedad',
                'verbose_name_plural': 'Propiedades',
            },
            bases=(webtooth.mixins.AuditModel, models.Model),
        ),
    ]
